language: php

php:
  - 5.3
  - 5.5

env:
  - DBTYPE=mysql TESTSUITE=Standalone
  - DBTYPE=sqlite TESTSUITE=Standalone
  - DBTYPE=postgres TESTSUITE=Standalone
  - DBTYPE=mysql TESTSUITE=MediaWiki
  - DBTYPE=sqlite TESTSUITE=MediaWiki
  - DBTYPE=postgres TESTSUITE=MediaWiki

matrix:
  allow_failures:
    - env: DBTYPE=postgres TESTSUITE=MediaWiki
    - env: DBTYPE=postgres TESTSUITE=Standalone
  exclude:
    - php: 5.3
      env: DBTYPE=postgres TESTSUITE=Standalone
    - php: 5.3
      env: DBTYPE=postgres TESTSUITE=MediaWiki


before_script: bash .travis.sh $TESTSUITE

script: cd ../phase3/extensions/WikibaseDatabase ; phpunit --testsuite=WikibaseDatabase$TESTSUITE

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikimedia-wikidata"
    on_success: change
    on_failure: always